# Generated by Django 3.2.24 on 2024-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.IntegerField(db_column='SNO', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='SName', max_length=100)),
                ('birthday', models.DateField(db_column='Birthday')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], db_column='Gender', max_length=100)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
    ]
