# Generated by Django 3.2.24 on 2024-03-13 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(db_column='Address', default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
